name: GitHub Actions Demo
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: prepare
        run: mkdir build && cd build
      - name: cmake
        run: cmake ..
      - name: build
        run: cmake --build .
