name: GitHub Actions Demo
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: prepare
        run: echo "Current path is ${{github.action_path}}"
      - name: list dict
        run: ls "${{github.action_path}}"
