name: GitHub Actions Demo
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull submodule
        run: FetchSDK.cmd
        shell: cmd

      - name: Download Server
        run: |
          mkdir D:/BDS
          ServerLink=$(cat 'LINK.txt')
          curl -L -o D:/BDS/server.zip "$ServerLink"
          unzip D:/BDS/server.zip -d D:/BDS > /dev/null
        shell: bash

      - name: Build Bedrock Library
        run: |
          ls
          cd SDK/Tools
          LibraryBuilder.exe -o ..\Lib D:\BDS 

      - name: Check Status
        run: |
          echo "Current path is ${{ github.workspace }}"
          mkdir build
          ls

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build