name: GitHub Actions Demo
on: [ push ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: prepare
        run: |
          echo "Current path is ${{ github.workspace }}"
          ls ${{github.workspace}}